config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "projects#index"

  resources :users do
    get 'tasks', to: 'users#tasks', as: 'tasks'
    get 'projects', to: 'users#projects', as: 'projects'
  end

  resources :projects do
    resources :work_tasks
  end
end

app/views/layouts/shared/_top_nav.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%=active_link_to root_path, class: "navbar-brand" do %>PM Dashboard<%end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Projects
          </a>
          <ul class="dropdown-menu">
            <li><%=active_link_to root_path, class: "dropdown-item", active: :exclusive do %>All Projects<%end %></li>
            <% if can? :create, Project %>
              <li><%=active_link_to user_projects_path(current_user), class: "dropdown-item", active: :exclusive do %>My Projects<%end %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%=active_link_to new_project_path, class: "dropdown-item", active: :exclusive do %>New Project<% end %></li>
            <% end %>
          </ul>
        </li>

        <li class="nav-item">
          <%=active_link_to user_tasks_path(current_user), class: "nav-link", active: :exclusive do %>My Tasks<%end %>
        </li>
      </ul>
    </div>

    <div class="float-end">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%=link_to edit_user_path(current_user), class: "me-2 btn btn-outline-info" do %><%=current_user.full_name.present? ? current_user.full_name : current_user.email %><% end %>
        </li>
        <li class="nav-item">
          <%=link_to destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" do %>Logout<% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>