config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "projects#index"

  resources :users do
    get 'tasks', to: 'users#tasks', as: 'tasks'
    get 'projects', to: 'users#projects', as: 'projects'
  end

  resources :projects do
    resources :work_tasks
  end
end

app/models/work_task.rb
class WorkTask < ApplicationRecord
  belongs_to :project
  belongs_to :user
  belongs_to :parent, class_name: "WorkTask", optional: true
  has_many :subtasks, class_name: "WorkTask", foreign_key: "parent_id", dependent: :destroy
  # the user to whom the task is assigned
  belongs_to :user_assignment, class_name: "User", foreign_key: "user_assignment_id", optional: true

  validates :title, presence: true
  validates :description, presence: true
  validates :due_date, presence: true
  validate :due_date_cannot_be_in_the_past, on: [:create, :update]

  # Delayed job is used to check if a task is overdue
  after_create :enqueue_job
  before_update :delete_and_reenqueue_job, if: :due_date_changed?
  before_destroy :delete_job

  # Status shows the progress of a work task
  enum status: %i[not_started working needs_review done late]
  after_initialize :set_default_status, if: :new_record?

  def set_default_status
    self.status ||= :not_started
  end

  # Work focus is a way to categorize work tasks
  enum work_focus: %i[development design business_research marketing sales other]
  after_initialize :set_default_work_focus, if: :new_record?

  def set_default_work_focus
    self.work_focus ||= :other
  end

  # Validate that a work task due date is not in the past
  def due_date_cannot_be_in_the_past
    formatted_date = due_date.strftime("%Y-%m-%d") rescue nil
    if due_date.present? && formatted_date.to_date <= Date.today
      errors.add(:due_date, "must be greater than today")
    end
  end

  # Always order ascending by due date unless otherwise specified
  default_scope { order(due_date: :asc) }

  # Scope to find top-level tasks only AKA not subtasks
  scope :top_level, -> { where(parent_id: nil) }

  # Check to see if a task has subtasks
  def has_subtasks?
    subtasks.any?
  end

  # Check to see if a task has a parent
  def has_parent?
    parent_id.present?
  end

  # Helper to see if an employee can change the status of a
  # task to something other than "working" or "needs_review"
  def can_employee_change_status?(new_status)
    %w[working needs_review].include?(new_status)
  end

  # Create new job to check if a task is overdue
  def enqueue_job
    jid = CheckTaskJob.perform_at(due_date.to_time.to_i, id)
    update_column(:sidekiq_job_id, jid)
  end
  # Delete the old job and create a new one
  def delete_and_reenqueue_job
    delete_job
    enqueue_job
  end
  # Delete the job if it exists
  def delete_job
    Sidekiq::ScheduledSet.new.find_job(sidekiq_job_id).try(:delete) if sidekiq_job_id
  end
end

app/controllers/work_tasks_controller.rb
class WorkTasksController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  def index
  end

  def show
    @work_task = WorkTask.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @work_task }
    end
  end

  def edit
    @work_task = WorkTask.find(params[:id])
    @parent_task = params[:parent_id].present? ? @work_task.parent : nil
  end

  def new
    @project = Project.find(params[:project_id])
    @parent_task = params[:parent_id].present? ? @project.work_tasks.find(params[:parent_id]) : nil
    @work_task = @project.work_tasks.new(parent: @parent_task)
  end

  def create
    @project = Project.find(params[:project_id])
    @work_task = @project.work_tasks.new(work_task_params)
    @work_task.user = current_user

    respond_to do |format|
      if @work_task.save
        if @work_task.has_parent?
          format.html { redirect_to project_work_task_path(@work_task.project, @work_task.parent), notice: "Work task was successfully created." }
          format.json { render json: @work_task, status: :created }
        else
          format.html { redirect_to project_path(@project), notice: "Work task was successfully created." }
          format.json { render json: @work_task, status: :created }
        end
      else
        format.html { render :new, alert: "Work task could not be created." }
        format.json { render json: @work_task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @work_task = WorkTask.find(params[:id])
    authorize! :update, @work_task

    # Only allow the status to be changed if the user is an employee and the task is not overdue
    if (@work_task.can_employee_change_status?(work_task_params[:status]) && current_user.employee?) || current_user.pm?
      respond_to do |format|
        if @work_task.update(work_task_params)
          format.html { redirect_to project_work_task_path(@work_task.project, @work_task), notice: "Task was successfully updated." }
          format.json { render json: @work_task, status: :ok, location: @work_task }
        else
          format.html { render :edit, alert: "Work task could not be updated." }
          format.json { render json: @work_task.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to project_work_task_path(@work_task.project, @work_task), alert: "You cannot change the status of this task to: #{work_task_params[:status].titleize}." }
        format.json { render json: { error: "You cannot change the status of this task to: #{work_task_params[:status].titleize}." }, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @work_task = current_user.work_tasks.find(params[:id])
    work_task = @work_task
    @work_task.destroy
    respond_to do |format|
      if work_task.has_parent?
        format.html { redirect_to project_work_task_path(work_task.project, work_task.parent), notice: "Work task was successfully deleted." }
        format.json { head :no_content }
      else
        format.html { redirect_to project_path(@work_task.project), notice: "Work task was successfully deleted." }
        format.json { head :no_content }
      end
    end
  end

  private

  def work_task_params
    params.require(:work_task).permit(:title, :description, :due_date, :status, :work_focus, :user_assignment_id, :parent_id)
  end
end

app/helpers/work_tasks_helper.rb
module WorkTasksHelper
  def subtask_status_bar(task)
    tasks = task.subtasks.to_a
    total_tasks = tasks.size
    return 0 if total_tasks.zero?

    done_tasks = tasks.count { |task| task.done? }
    (done_tasks.to_f / total_tasks * 100).round(2)
  end

  def subtask_status_button_group(status, task)
    classes = "btn"
    (status == task.status) ? classes += " active btn-outline-primary" : classes += " btn-outline-secondary"
    link_to project_work_task_path(@work_task.project, @work_task, "work_task[status]": status), method: :patch, class: classes, data: { confirm: "Are you sure?" } do
      "#{status.titleize}"
    end
  end

  def work_task_status_class(work_task)
    if work_task.due_date < Date.today
      "bg-danger"
    elsif work_task.due_date < Date.today + 7
      "bg-warning"
    end
  end

  def work_task_status_text(work_task)
    if work_task.due_date < Date.today
      "Late"
    elsif work_task.due_date < Date.today + 7
      "Due Soon"
    end
  end
end

app/views/work_tasks/_form.html.erb
<%= form_for [project, work_task] do |form| %>
  <div class="row">
    <%=form.hidden_field :parent_id, value: parent_task ? parent_task.id : nil %>
    <div class="col-6">
      <%=form.label :title, class: "form-label"%>
      <%=form.text_field :title, class: "form-control"%>
    </div>
    <div class="col-6">
      <%=form.label :status, class: "form-label"%>
      <%=form.select :status, WorkTask.statuses.keys.map { |s| [s.titleize, s] }, {}, class: "form-select"%>
    </div>

    <div class="col-6">
      <%=form.label :work_focus, class: "form-label"%>
      <%=form.select :work_focus, WorkTask.work_focus.keys.map { |w| [w.titleize, w] }, {}, class: "form-select"%>
    </div>

    <div class="col-6">
      <%=form.label :user_assignment_id, class: "form-label"%>
      <%=form.select :user_assignment_id, User.all.map { |u| [u.email, u.id] }, {}, class: "form-select"%>
    </div>

    <div class="col-12">
      <%=form.label :description, class: "form-label"%>
      <%=form.text_area :description, class: "form-control"%>
    </div>

    <div class="col-12">
      <%=form.label :due_date, class: "form-label"%>
      <%=form.text_field :due_date, value: work_task.due_date ? work_task.due_date.strftime("%Y-%m-%d") : Date.today.strftime("%Y-%m-%d"), class: "form-control"%>
    </div>

    <div class="col-12 mt-3">
      <%=link_to "Cancel", :back, class: "btn btn-outline-secondary" %>
      <%=form.submit "Create", class: "btn btn-primary float-end"%>
    </div>
  </div>
<% end %>

app/views/work_tasks/_subtask_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Task</th>
      <th>Status</th>
      <th>Due Date</th>
      <th>Assignment</th>
    </tr>
  </thead>
  <tbody>
    <% subtasks.each do |task| %>
      <tr>
        <td><%= link_to task.title, project_work_task_path(task.project, task) %></td>
        <td><%= task.status.titleize %></td>
        <td><%= task.due_date.strftime("%m/%d/%Y") %></td>
        <td><%= task.user_assignment.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/work_tasks/_task_table.html.erb
<table class="table">
  <tr>
    <th>Task</th>
    <th>Status</th>
    <th>Due Date</th>
    <th>Progress</th>
  </tr>
  <% work_tasks.each do |task| %>
    <tr class="<%=work_task_status_class(task) %>">
      <td>
        <% if show_project %>
          [<%= link_to task.project.title, project_path(task.project) %>]
        <% end %>

        <% if work_task_status_text(task) %>
          <span class="badge text-bg-info"><%=work_task_status_text(task) %></span>
        <% end %>
        <%= link_to task.title, project_work_task_path(task.project, task) %>
      </td>
      <td><%= task.status.titleize %></td>
      <td><%= task.due_date %></td>
      <td>
        <% if task.has_subtasks? %>
          <div class="progress mt-1" role="progressbar" aria-label="Basic example" aria-valuenow="<%=subtask_status_bar(task) %>" aria-valuemin="0" aria-valuemax="100">
            <div class="progress-bar" style="width: <%=subtask_status_bar(task) %>%"></div>
          </div>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/work_tasks/edit.html.erb
<div class="row">
  <div class="col-12">
    <h2>Edit: <%=@work_task.title %></h2>
  </div>
  <div class="col-12" data-controller="project-form">
    <%= render partial: "form", locals: { parent_task: @parent_task, project: @work_task.project, work_task: @work_task } %>
  </div>
</div>

app/views/work_tasks/index.html.erb
<h1>WorkTasks#index</h1>
<p>Find me in app/views/work_tasks/index.html.erb</p>

app/views/work_tasks/new.html.erb
<div class="row">
  <div class="col-12">
    <% if @parent_task %>
      <h2>New Sub-Task for: <%=@parent_task.title %></h2>
    <% else %>
      <h2>New Task for: <%=@project.title %></h2>
    <% end %>
  </div>
  <div class="col-12" data-controller="project-form">
    <%= render partial: "form", locals: { parent_task: @parent_task, project: @project, work_task: @work_task } %>
  </div>
</div>

app/views/work_tasks/show.html.erb
<% content_for :action_bar do %>
  <div class="row justify-content-end">
    <div class="col-2">
      <% if can? [:update, :delete], @work_task %>
        <div class="btn-group float-end" role="group">
          <%= link_to project_work_task_path(@work_task.project, @work_task), method: :delete, data: {confirm: "Are you sure?"}, class: "float-end btn btn-outline-danger" do %>Delete<% end %>
          <% if @work_task.has_parent? %>
            <%= link_to edit_project_work_task_path(@work_task.project, @work_task, parent_id: @work_task.parent.id), class: "float-end btn btn-outline-secondary" do %>Edit<% end %>
          <% else %>
            <%= link_to edit_project_work_task_path(@work_task.project, @work_task), class: "float-end btn btn-outline-secondary" do %>Edit<% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="col-12">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">Project: <%=link_to @work_task.project.title, project_path(@work_task.project) %></li>
        <% if @work_task.has_parent? %>
          <li class="breadcrumb-item" aria-current="page"><%=link_to @work_task.parent.title, project_work_task_path(@work_task.project, @work_task.parent) %></li>
        <% end %>
        <li class="breadcrumb-item active" aria-current="page"><%=@work_task.title %></li>
      </ol>
    </nav>
  </div>
  <div class="col-12">
    <h2><%=@work_task.title %></h2>
  </div>
  <div class="col-8">
    <p><%=@work_task.description %></p>

    <div class="row mb-3">
      <div class="col">
        <h4>Update Status</h4>
        <div class="btn-group" role="group">
          <% WorkTask.statuses.keys.each do |status| %>
            <%=subtask_status_button_group(status, @work_task) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="col-4">
    <ul>
      <li>Assigned to: <span class="badge text-bg-primary"><%=@work_task.user_assignment.email %></span></li>
      <li>Created by: <span class="badge text-bg-secondary"><%=@work_task.user.email %></span></li>
      <li>Due on: <%=@work_task.due_date.strftime("%m/%d/%Y") %></li>
    </ul>
  </div>
</div>

<% if !@work_task.has_parent? %>
<div class="row mt-3">
  <div class="col-6">
    <h3>Sub Tasks</h3>
  </div>
  <div class="col-6">
    <%=link_to "New Subtask", new_project_work_task_path(@work_task.project, parent_id: @work_task.id), class: "btn btn-primary btn-sm float-end" %>
  </div>
  <div class="col-12">
    <%=render partial: "subtask_table", locals: { subtasks: @work_task.subtasks } %>
  </div>
</div>
<% end %>