config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "projects#index"

  resources :users do
    get 'tasks', to: 'users#tasks', as: 'tasks'
    get 'projects', to: 'users#projects', as: 'projects'
  end

  resources :projects do
    resources :work_tasks
  end
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :work_tasks, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
  validates :due_date, presence: true
  validate :due_date_cannot_be_in_the_past, on: [:create, :update]

  def due_date_cannot_be_in_the_past
    formatted_date = due_date.strftime("%Y-%m-%d") rescue nil
    if due_date.present? && formatted_date.to_date <= Date.today
      errors.add(:due_date, "must be greater than today")
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  def index
    @projects = Project.all.order(due_date: :asc).includes(:work_tasks)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  def show
    @project = Project.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  def new
    @project = current_user.projects.new
  end

  def create
    @project = current_user.projects.new(project_params)

    respond_to do |format|
      if @project.save
        puts @project.inspect
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render :new, alert: 'Failed to create project.' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render json: @project, status: :ok }
      else
        format.html { render :edit, alert: 'Failed to update project.' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def project_params
      params.require(:project).permit(:title, :description, :due_date)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def project_status_bar(project)
    tasks = project.work_tasks.to_a
    total_tasks = tasks.size
    return 0 if total_tasks.zero?

    done_tasks = tasks.count { |task| task.done? }
    (done_tasks.to_f / total_tasks * 100).round(2)
  end

  def project_status_class(project)
    if project.due_date < Date.today
      "bg-danger"
    elsif project.due_date < Date.today + 7
      "bg-warning"
    end
  end

  def project_status_text(project)
    if project.due_date < Date.today
      "Late"
    elsif project.due_date < Date.today + 7
      "Due Soon"
    end
  end
end

app/views/projects/_form.html.erb
<%=form_for @project do  |form|%>
  <% if @project.errors %>
    <ul>
      <% @project.errors.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="col-12">
    <%=form.label :title, class: "form-label"%>
    <%=form.text_field :title, class: "form-control"%>
  </div>
  <div class="col-12">
    <%=form.label :description, class: "form-label"%>
    <%=form.text_area :description, class: "form-control"%>
  </div>

  <div class="col-12">
    <%=form.label :due_date, class: "form-label"%>
    <%=form.text_field :due_date, value: @project.due_date ? @project.due_date.strftime("%Y-%m-%d") : Date.today.strftime("%Y-%m-%d"), class: "form-control"%>
  </div>

  <div class="col-12 mt-3">
    <%=link_to "Cancel", :back, class: "btn btn-outline-secondary" %>
    <button class="btn btn-primary float-end" type="submit">Save</button>
  </div>
<% end %>

app/views/projects/_project_table.html.erb
<div class="row">
  <div class="col-12">
    <table class="table">
      <thead>
      <tr>
        <th scope="col">Title</th>
        <th scope="col">Due Date</th>
        <th scope="col">Description</th>
        <th scope="col">Tasks</th>
        <th scope="col">Progress</th>
      </tr>
      </thead>
      <tbody>
      <% projects.each do |project| %>
        <tr class="<%=project_status_class(project) %>">
          <td>
            <% if project_status_text(project) %>
              <span class="badge text-bg-info"><%=project_status_text(project) %></span>
            <% end %>
            <%= link_to project.title, project_path(project) %>
          </td>
          <td><%= project.due_date.strftime("%m/%d/%Y") %></td>
          <td><%= project.description.truncate(60, separator: ' ') %></td>
          <td><%= project.work_tasks.size %></td>
          <td>
            <div class="progress mt-1" role="progressbar" aria-label="Basic example" aria-valuenow="<%=project_status_bar(project) %>" aria-valuemin="0" aria-valuemax="100">
              <div class="progress-bar" style="width: <%=project_status_bar(project) %>%"></div>
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/projects/edit.html.erb
<div data-controller="project-form" data-project-form-duedate-value="<%=@project.due_date %>">
  <%= render partial: "form", with: @project %>
</div>

app/views/projects/index.html.erb
<div class="row">
  <div class="col-12">
    <h2>All Projects</h2>
  </div>
  <div class="col-12">
    <%= render partial: "project_table", locals: { projects: @projects } %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="row" data-controller="project-form">
  <div class="col-md-12">
    <%= render partial: "form", with: @project %>
  </div>
</div>

app/views/projects/show.html.erb
<% content_for :action_bar do %>
  <div class="row justify-content-end">
    <div class="col-2">
      <div class="btn-group float-end" role="group" aria-label="Basic example">
        <%= link_to project_path(@project), method: :delete, data: {confirm: "Are you sure?"}, class: "float-end btn btn-outline-danger" do %>Delete<% end %>
        <%= link_to edit_project_path(@project), class: "float-end btn btn-outline-secondary" do %>Edit<% end %>
      </div>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-12">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">Project: <%=@project.title %></li>
      </ol>
    </nav>
  </div>

  <div class="col-12">
    <h2>Project: <%=@project.title %></h2>
    <p><em><%=@project.description %></em></p>
  </div>

  <div class="col-6">
    <h3>Tasks</h3>
  </div>
  <div class="col-6">
    <%= link_to new_project_work_task_path(@project), class: "float-end btn btn-outline-primary btn-sm" do %>New Task<% end %>
  </div>

  <div class="col-12">
      <%=render partial: "work_tasks/task_table", locals: { work_tasks: @project.work_tasks.top_level, show_project: false } %>
  </div>

</div>